name: wan_sr
channels:
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - pip
  - gurobi=9.1.2
  - matplotlib=3.1.3
  - seaborn
  - networkx=2.5.1
  - numpy=1.20.3
  - python=3.7.10
  - scipy=1.6.3
  - networkit=8.1
  - pandas=1.3.3
